### ISSUE TITLE
Export impossible COCO/VOC/YOLO format

### ISSUE THREAD

**Issue by Theo-HENAFF** [heartexlabs/label-studio-converter#41]
I'm unable to export my annotations in COCO/VOC/YOLO format in a newly created project (for object detection, ~300 images, ~300 annotations, with only 2 classes in rectangle labels).

Here is my stacktrace for Yolo export ( IndexError also in VOC/COCO ): 
```
Traceback (most recent call last):
  File "/home/Theo.Henaff/miniconda3/envs/yolo_v5_env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/Theo.Henaff/miniconda3/envs/yolo_v5_env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Theo.Henaff/miniconda3/envs/yolo_v5_env/lib/python3.8/site-packages/label_studio/data_export/api.py", line 103, in get
    export_stream, content_type, filename = DataExport.generate_export_file(project, tasks, export_type, request.GET)
  File "/home/Theo.Henaff/miniconda3/envs/yolo_v5_env/lib/python3.8/site-packages/label_studio/data_export/models.py", line 83, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/home/Theo.Henaff/miniconda3/envs/yolo_v5_env/lib/python3.8/site-packages/label_studio_converter/converter.py", line 172, in convert
    self.convert_to_yolo(input_data, output_data, output_image_dir=image_dir,
  File "/home/Theo.Henaff/miniconda3/envs/yolo_v5_env/lib/python3.8/site-packages/label_studio_converter/converter.py", line 565, in convert_to_yolo
    category_name = label['rectanglelabels'][0]
IndexError: list index out of range
```

My labelling template is based on previous working projects (where exports were fine) : 
```
<View style="display:flex;align-items:start;gap:8px;flex-direction:column-reverse">
  <Image name="image" value="$image" zoom="true" rotateControl="true" zoomControl="true"/>
  <Filter toName="label" minlength="0" name="filter"/>
  <RectangleLabels name="label" toName="image" showInline="true">
    <Label value="Iban" background="#995AE6"/>
    <Label value="TitulaireCompte" background="#43E6CD"/>
  </RectangleLabels>
</View>
```
Working with label-studio 1.1, python 3.8 in conda env, ubuntu 20.04

I have annotate the same images in another project (with different albels) and it was fine. I have also done much bigger projects and they exported without errors.
The problem seems to come from my side but I have no clue about how to it has come / how to resolve it.

**Comment by Theo-HENAFF** [comment]
After looking at each annotations in the project I found one rectangle-label without any class attached, after deleting it it worked fine again.
It may be a good idea to ignore (or get the possibility to ignore) these no-class annotations while exporting.
